CREATE TABLE administradores
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome  VARCHAR(20)  NOT NULL,
    cpf   VARCHAR(14)  NOT NULL,
    senha VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE categorias
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE contas
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario     INTEGER     NOT NULL,
    nome_conta     VARCHAR(20) NOT NULL,
    banco          VARCHAR(3)  NOT NULL,
    agencia        VARCHAR(6)  NOT NULL,
    conta_corrente VARCHAR(6)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE lancamentos
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_conta     INTEGER        NOT NULL,
    id_categoria INTEGER        NOT NULL,
    valor        decimal(10, 2) NOT NULL,
    operacao     varchar(1)     NOT NULL,
    data         date           NOT NULL,
    descricao    varchar(100) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome     varchar(20)  NOT NULL,
    cpf      varchar(14)  NOT NULL,
    senha    varchar(255) NOT NULL,
    suspenso varchar(1)   NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE contas
    ADD FOREIGN KEY (id_usuario) REFERENCES usuarios (id);
ALTER TABLE lancamentos
    ADD FOREIGN KEY (id_categoria) REFERENCES categorias (id);
ALTER TABLE lancamentos
    ADD FOREIGN KEY (id_conta) REFERENCES contas (id);

INSERT INTO usuarios (nome, cpf, senha, suspenso)
VALUES ('leo', '870.304.050-05', '111', 'N'),
       ('maria', '167.740.300-41', '111', 'N');

INSERT INTO administradores (nome, cpf, senha)
VALUES ('leo', '249.252.810-38', '111');

INSERT INTO categorias (descricao)
VALUES ('água'),
       ('luz'),
       ('condomínio'),
       ('plano de saúde'),
       ('salário');

INSERT INTO contas (id_usuario, nome_conta, banco, agencia, conta_corrente)
VALUES (1, 'conta itaú', '341', '12321', '1234-6'),
       (2, 'conta bb', '001', '5678', '9521-0');

INSERT INTO lancamentos (id_conta, id_categoria, valor, operacao, data, descricao)
VALUES (1, 3, 790.00, 'D', '2021-06-11', 'Pago com atraso'),
       (1, 2, 200.00, 'D', '2021-06-11', ''),
       (2, 1, 600.90, 'D', '2021-06-11', ''),
       (2, 2, 350.56, 'D', '2021-06-11', ''),
       (1, 5, 1590.88, 'C', '2021-06-15', NULL),
       (2, 5, 2135.00, 'C', '2021-06-11', NULL);
